language: cpp

dist: bionic

os:
    - linux

compiler:
    - clang
    - gcc

before_install:
    - build/travis/prebuild

#install:

script:
    - build/travis/build

notifications:
    email:
        on_success: change
        on_failure: always
